version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '00:00'
    commit-message:
      prefix: 'fix(deps)'
    labels:
      - 'Scope: Dependencies'
      - 'Type: Maintenance'
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: '-'
    rebase-strategy: 'auto'
    groups:
      default:
        patterns:
          - '*'
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '00:00'
    commit-message:
      prefix: 'ci'
      prefix-development: 'dev'
      include: 'scope'
    labels:
      - 'Scope: Dependencies'
      - 'Type: Maintenance'
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: '-'
    rebase-strategy: 'auto'
    groups:
      default:
        patterns:
          - '*'
