name: Build
on:
  schedule:
    - cron: '55 */4 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - name: Build and test through WARP
        env:
          CI: true
        run: .github/scripts/ci-warp.sh run 'npm run build && npm test'
      - run: git checkout -- package-lock.json #prevent package-lock.json-only feat changes
      - uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          skip_dirty_check: false
          commit_message: 'fix: new patchlogs'
          commit_user_name: wfcd-bot-boi
          commit_user_email: botboi@warframestat.us
          commit_author: wfcd-bot-boi <botboi@warframestat.us>
