name: Build
on:
  schedule:
    - cron: '55 */4 * * *'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - name: Tailscale
        uses: tailscale/github-action@780049a30b6ff5c378a9e7b389d15ece7a204888 # v4.1.3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - run: npm run build
        env:
          PROXY_URL: ${{ secrets.SOLVERR_PROXY_URL }}
      - run: npm test
      - run: git checkout -- package-lock.json #prevent package-lock.json-only feat changes
      - uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          skip_dirty_check: false
          commit_message: 'fix: new patchlogs'
          commit_user_name: wfcd-bot-boi
          commit_user_email: botboi@warframestat.us
          commit_author: wfcd-bot-boi <botboi@warframestat.us>
